service: service

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 20
  environment:
    GRIP_URL: ${env:GRIP_URL}

custom:
  services: src/services
  index: ${self:custom.services}/index

package:
  individually: true
  include:
    ${self:custom.index}.ts

functions:
  api:
    handler: ${self:custom.index}.handler
    events:
      - http:
          cors: true
          path: /{proxy+}
          method: any