service: service

plugins:
  - window-hack
  - serverless-offline
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 20
  environment:
    NODE_ENV: ${env:NODE_ENV}
    GRIP_URL: ${env:GRIP_URL_PROD}
    NODE_PRESERVE_SYMLINKS: ${env:NODE_PRESERVE_SYMLINKS}

custom:
  serverless-offline:
    port: 9090
    host: 0.0.0.0
  api: api
  index: ${self:custom.api}/index

package:
  individually: true
  exclude:
    - ".*/**"
  include:
    - ${self:custom.index}.js

functions:
  api:
    handler: ${self:custom.index}.handler
    events:
      - http:
          cors: true
          path: /{proxy+}
          method: any