service: service

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - node_modules/**/*
  include:
    src/services/Messages.ts

functions:
  messages:
    handler: src/services/Messages.handler
    events:
      - http:
          path: messages/{id?}
          method: get
          request:
            parameters:
              paths:
                id: true